experiment_name: p3-core-evals
nanochat_ref: p3-log-every
gpu: A100-80GB

train: []

eval:
  - checkpoint: pico-short
    step: 1433
    evals: [core]

  - checkpoint: pico-short
    step: 1450
    evals: [core]

  - checkpoint: pico-short
    step: 1500
    evals: [core]

  - checkpoint: pico-short
    step: 1550
    evals: [core]

  - checkpoint: pico-short
    step: 1600
    evals: [core]

  - checkpoint: pico-short
    step: 1650
    evals: [core]

  - checkpoint: pico-short
    step: 1700
    evals: [core]

  - checkpoint: pico-short
    step: 1750
    evals: [core]

  - checkpoint: pico-short
    step: 1800
    evals: [core]

  - checkpoint: pico-short
    step: 1850
    evals: [core]

  - checkpoint: pico-short
    step: 1900
    evals: [core]
