include classpath("application.conf")

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}

queues {
  fast-path { }
  normalizer { }
  precedent { }
  ml-inference { }
  agent { }
  resolution { }
  posting { }
  flywheel { }
}
